# Use the official Node.js 18 image as the base image
FROM node:18.17.0-alpine3.18

# Set the working directory inside the container
WORKDIR /app

# Copy package.json and package-lock.json to the container
COPY package.json package-lock.json ./

# Install project dependencies
RUN npm install

# Copy the entire application code to the container
COPY . .

# Expose the default Next.js port (change it if necessary)
EXPOSE 3000

# Start the development server 
CMD ["npm", "run", "dev"]
