version: "3"
services:
  app:
    container_name: harley-app
    profiles: ["server"]
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - .:/app
      - /app/node_modules
    ports:
      - 3000:3000
    depends_on:
      - db
    command: npm run dev
    environment:
      - MONGODB_URI=mongodb://db:27017/harley-db

  db:
    container_name: harley-mongodb
    image: mongo:latest
    profiles: ["server", "seeding"]
    volumes:
      - mongodb_data_container:/data/db
    ports:
      - 27017:27017

  seeding:
    container_name: seeding-harley-mongodb
    image: ghcr.io/pkosiec/mongo-seeding:3.7.2
    profiles: ["seeding"]
    environment:
      - DB_NAME=harley-db
      - REPLACE_ID=true
      - SET_TIMESTAMPS=true
      - DROP_DATABASE=false
    volumes:
      - .:/app
    working_dir: /app/data-seeds
    network_mode: host
    depends_on:
      - db

volumes:
  mongodb_data_container:
